### ISSUE TITLE
`RuntimeError: CUDA error: an illegal memory access was encountered`

### ISSUE THREAD

**Issue by AndreaGuarracino** [lbcb-sci/herro#24]
I tried this command

```shell
apptainer run --nv \                                                                 
    --bind "/scratch":"/output" \
    --bind "/lizardfs/guarracino/ratty/sequencing-data/HXB10/ONT":"/input" \
    --bind "/lizardfs/guarracino/git/herro/resources":"/models" \
    herro.sif inference -d 0,1 -t 8 -b 32 -m /models/model_v0.1.pt /input/HXB10.fq.gz /output/HXB10.herro.fq.gz
```

I got this error:

```shell
INFO:    underlay of /etc/localtime required more than 50 (77) bind mounts
INFO:    underlay of /usr/bin/nvidia-debugdump required more than 50 (308) bind mounts
[00:03:31] Parsed 430454 reads.                                                                                                                                          
[00:52:46] Processing 1/? batch ⠄                                                                                                                                        
[00:52:46] Processing 1/? batch ⡀                                                                                                                                        
[00:55:02] Processing 1/? batch ⠁
[>---------------------------------------] 2/94965                                                                                                                       [W graph_fuser.cpp:108] Warning: operator() profile_node %1243 : int[] = prim::profile_ivalue(%1241)
[00:55:12] Processing 1/? batch ⠂
[>---------------------------------------] 19/94965                                                                                                                      thread '<unnamed>' panicked at src/inference.rs:172:64:
called `Result::unwrap()` on an `Err` value: Torch("The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__/transformer.py\", line 26, in forward\n      _2 = torch.select(x2, 0, i)\n      _3 = annotate(List[Optional[Tensor]], [tp])\n      _4 = torch.append(batch, torch.index(_2, _3))\n                               ~~~~~~~~~~~ <--- HERE\n    x3 = _0(batch, True, 0., )\n    _5 = __torch__.transformer.create_mask(lengths, )\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"/raid/scratch/stanojevicd/projects/haec-BigBird/transformer.py\", line 40, in forward\n        x = x.squeeze(-1).transpose(1, 2)  # [B, L, 256]\n    \n        batch = [x[i, tp] for i, tp in enumerate(target_positions)]\n                 ~~~~~~~~ <--- HERE\n        x = nn.utils.rnn.pad_sequence(batch, True)\n        mask = create_mask(lengths).to(device=x.device)\nRuntimeError: CUDA error: an illegal memory access was encountered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Can you help me?

**Comment by dominikstanojevic** [comment]
Hi Andrea,

can you set CUDA_LAUNCH_BLOCKING=1 environment variable and try again? This should give us a more detailed error description.

Best regards,
Dominik

**Comment by AndreaGuarracino** [comment]
This way?

```shell
CUDA_LAUNCH_BLOCKING=1 apptainer run --nv \                                                                                                                                                                             
    --bind "/scratch":"/output" \
    --bind "/lizardfs/guarracino/ratty/sequencing-data/HXB10/ONT":"/input" \
    --bind "/lizardfs/guarracino/git/herro/resources":"/models" \
    herro.sif inference -d 0,1 -t 8 -b 32 -m /models/model_v0.1.pt /input/HXB10.fq.gz /output/HXB10.herro.fq.gz
INFO:    underlay of /etc/localtime required more than 50 (77) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (308) bind mounts
[00:03:57] Parsing reads ⠇                                                                                                                                                                                                    
[00:03:59] Parsing reads ⠧                                                                                                                                                                                                                                                                    
[00:03:59] Parsing reads ⠇                                                                                                                                                                                                                                                                    
[00:03:59] Parsing reads ⠏                                                                                                                                                                                                                                                                    
[00:04:06] Parsed 430454 reads.                                                                                                                                                                                                                                                               
[00:54:43] Processing 1/? batch ⠄
[>---------------------------------------] 2/94965                                                                                                                                                                                                                                            
[W graph_fuser.cpp:108] Warning: operator() profile_node %1243 : int[] = prim::profile_ivalue(%1241)
[00:54:53] Processing 1/? batch ⠈
[>---------------------------------------] 20/94965                                                                                                                                                                                                                                           
thread '<unnamed>' panicked at src/inference.rs:172:64:
called `Result::unwrap()` on an `Err` value: Torch("The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__/model.py\", line 36, in forward\n    x0 = torch.permute(x, [0, 3, 1, 2])\n    qn = self.qn\n    sliced_sequences_concatenated = (qn).forward(x0, target_positions, lengths, )\n                                     ~~~~~~~~~~~ <--- HERE\n    fc2 = self.fc2\n    _1 = (fc2).forward(sliced_sequences_concatenated, )\n  File \"code/__torch__/transformer.py\", line 16, in forward\n    _0 = __torch__.torch.nn.utils.rnn.pad_sequence\n    context_read = self.context_read\n    x0 = (context_read).forward(x, )\n          ~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n    context_pos = self.context_pos\n    x1 = (context_pos).forward(x0, )\n  File \"code/__torch__/torch/nn/modules/container.py\", line 14, in forward\n    _1 = getattr(self, \"1\")\n    _2 = getattr(self, \"2\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    return (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/conv.py\", line 23, in forward\n    weight = self.weight\n    bias = self.bias\n    _0 = (self)._conv_forward(input, weight, bias, )\n          ~~~~~~~~~~~~~~~~~~~ <--- HERE\n    return _0\n  def _conv_forward(self: __torch__.torch.nn.modules.conv.Conv2d,\n  File \"code/__torch__/torch/nn/modules/conv.py\", line 29, in _conv_forward\n    weight: Tensor,\n    bias: Optional[Tensor]) -> Tensor:\n    _1 = torch.conv2d(input, weight, bias, [1, 1], [8, 0], [1, 1])\n         ~~~~~~~~~~~~ <--- HERE\n    return _1\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"/raid/scratch/stanojevicd/projects/haec-BigBird/model.py\", line 157, in forward\n        sliced_sequences_concatenated = torch.cat(encoded)'''\n        x = x.permute((0, 3, 1, 2))\n        sliced_sequences_concatenated = self.qn(x, target_positions, lengths)\n                                        ~~~~~~~ <--- HERE\n    \n        # list of tensors of shape (selected_token_number, 1) -> (selected_token_number)\n  File \"/raid/scratch/stanojevicd/projects/haec-BigBird/transformer.py\", line 36, in forward\n    def forward(self, x: Tensor, target_positions: List[Tensor],\n                lengths: Tensor) -> Tensor:\n        x = self.context_read(x)  # [B, I, L, R] -> [B, 128, L, R]\n            ~~~~~~~~~~~~~~~~~ <--- HERE\n        x = self.context_pos(x)  # [B, 128, L, R] -> [B, 256, L, 1]\n        x = x.squeeze(-1).transpose(1, 2)  # [B, L, 256]\n  File \"/home/stanojevicd/miniforge3/envs/haec/lib/python3.11/site-packages/torch/nn/modules/container.py\", line 215, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"/home/stanojevicd/miniforge3/envs/haec/lib/python3.11/site-packages/torch/nn/modules/conv.py\", line 460, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return self._conv_forward(input, self.weight, self.bias)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"/home/stanojevicd/miniforge3/envs/haec/lib/python3.11/site-packages/torch/nn/modules/conv.py\", line 456, in _conv_forward\n                            weight, bias, self.stride,\n                            _pair(0), self.dilation, self.groups)\n        return F.conv2d(input, weight, bias, self.stride,\n               ~~~~~~~~ <--- HERE\n                        self.padding, self.dilation, self.groups)\nRuntimeError: CUDA error: an illegal memory access was encountered\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by dominikstanojevic** [comment]
Hi Andrea,

which GPU are you using, and what is its available VRAM? Thanks.

**Comment by AndreaGuarracino** [comment]
We have 8 Nvidia RTX 6000 Ada GPUs, 48 GB each

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AndreaGuarracino** [comment]
`-b 16` fixed the issue!
