### ISSUE TITLE
Out of bounds for 2-bit sequence decoding.

### ISSUE THREAD

**Issue by jguhlin** [lbcb-sci/herro#27]
Getting the following error:

```
❯ nice nice singularity run --nv herro.sif inference -m model_R9_v0.1.pt -b 64 --read-alns batched_alignments out.fastq.gz corrected
[00:44:38] Parsed 9283361 reads.
[00:03:06] Processing 1/? batch ⠠
[>---------------------------------------] 3/68175
[W graph_fuser.cpp:108] Warning: operator() profile_node %1243 : int[] = prim::profile_ivalue(%1241)
[00:04:51] Processing 1/? batch ⢀
[>---------------------------------------] 844/68175
thread '<unnamed>' panicked at /herro/src/haec_io.rs:144:9:
Out of bounds for 2-bit sequence decoding.
[00:04:51] Processing 1/? batch ⠐
[>---------------------------------------] 844/68175                                                                                      0:     0x5567db11c2b1 - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5567db11c2b1 - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5567db11c2b1 - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5567db11c2b1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5567db067390 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x5567db067390 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x5567db11a3ff - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x5567db11c094 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5567db11c094 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5567db11d4a7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x5567db11d205 - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x5567db11da40 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x5567db11d7b9 - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
13:     0x5567db11c776 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5567db11d572 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x5567dafff975 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x5567db094cd6 - herro::features::extract_features::{{closure}}::h3588956aabde7bf6
  17:     0x5567db0944a4 - core::slice::sort::insertion_sort_shift_left::h6a8cb7ba2acaadd2
  18:     0x5567db093da6 - core::slice::sort::merge_sort::ha0f0096f1486e1d5
  19:     0x5567db0ac7b8 - herro::features::extract_features::h00ea577d98be430b
  20:     0x5567db0b5a6d - std::sys_common::backtrace::__rust_begin_short_backtrace::hd2c9f1af20faea53
  21:     0x5567db0d0be6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h44881a552781c61d
  22:     0x5567db121375 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  23:     0x5567db121375 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  24:     0x5567db121375 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7f0a5d66bac3 - <unknown>
  26:     0x7f0a5d6fca04 - __clone
  27:                0x0 - <unknown>
Aborted (core dumped)
```

**Comment by dominikstanojevic** [comment]
Hello Joseph,

interesting. Can you please check for me if your input data (fastq) file contains only canonical (A, C, G, T) bases? Thanks.

Best regards,
Dominik

**Comment by peterdfields** [comment]
I see this same error. There does not appear to be non-canonical bases in the fastq file which resulted from the preprocess.sh script. Would any additional info be helpful to troubleshoot the error?

**Comment by wuyiwen-genomics-cn** [comment]
Hi, same problem here. Have you figured it out?

**Comment by jguhlin** [comment]
Hey, no, I never figured it out. My data does only contain canonical bases, as it is direct from Dorado output with some length filtering. Hoping to give this another try soon though.

**Comment by dominikstanojevic** [comment]
Hi,

I will try to add some checks later today (and push it to a separate branch). Please help me test later. Thanks.

Best,
Dominik

**Comment by dominikstanojevic** [comment]
Hi,

can you please build the tool from this branch (https://github.com/lbcb-sci/herro/tree/decoding-debug) and run it on your data? I added some checks for the length consistency so we should get a more descriptive error message now. 

Your feedback would help us to improve this tool. If we get the output we expect, we will push the changes into the main branch.

Best,
Dominik

**Comment by wuyiwen-genomics-cn** [comment]
> Hey, no, I never figured it out. My data does only contain canonical bases, as it is direct from Dorado output with some length filtering. Hoping to give this another try soon though.

FYI, if I followed the official procedure (preprocess.sh, porechop etc), no such error.

**Comment by lizakulaeva** [comment]
I've faced same error and backtraced it with RUST_BACKTRACE=full

```shell
Out of bounds for 2-bit sequence decoding.
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: herro::features::extract_features::{{closure}}
   3: core::slice::sort::shared::smallsort::small_sort_general_with_scratch
   4: core::slice::sort::stable::quicksort::quicksort
   5: core::slice::sort::stable::drift::sort
   6: core::slice::sort::stable::driftsort_main
   7: herro::features::extract_features
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
``` 

@dominikstanojevic I've also run it with decoding-debug branch, but nothing really changed. Did you figure out why this error is occuring? I've used dorado basecaller fastq output without any non-canonical bases and then followed herro pipeline (and there was no Ns in the fastq). Thank you!
