### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by unavailable-2374** [lbcb-sci/herro#66]
Hi developer,

Recently I used hero, as this command line:
RUST_BACKTRACE=full singularity run --nv --bind /scratch/shuoc/HG:/mnt/data:rw  herro.sif inference --read-alns /mnt/data/stats -t 128  -m /mnt/data/model_R10_v0.1.pt -b 128 /mnt/data/mini.fastq.gz /mnt/data/mini.fa

But it shows:
[00:13:17] Parsed 1604128 reads.                                                                                         [00:00:36] Processing 1/? batch ⠂
[>---------------------------------------] 1/32354                                                                       [W graph_fuser.cpp:108] Warning: operator() profile_node %1243 : int[] = prim::profile_ivalue(%1241)
[00:01:36] Processing 2/? batch ⠈
[>---------------------------------------] 1065/63886                                                                    thread '<unnamed>' panicked at src/inference.rs:184:64:
called `Result::unwrap()` on an `Err` value: Torch("The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__/model.py\", line 36, in forward\n    x0 = torch.permute(x, [0, 3, 1, 2])\n    qn = self.qn\n    sliced_sequences_concatenated = (qn).forward(x0, target_positions, lengths, )\n                                     ~~~~~~~~~~~ <--- HERE\n    fc2 = self.fc2\n    _1 = (fc2).forward(sliced_sequences_concatenated, )\n  File \"code/__torch__/transformer.py\", line 18, in forward\n    x0 = (context_read).forward(x, )\n    context_pos = self.context_pos\n    x1 = (context_pos).forward(x0, )\n          ~~~~~~~~~~~~~~~~~~~~ <--- HERE\n    x2 = torch.transpose(torch.squeeze(x1, -1), 1, 2)\n    batch = annotate(List[Tensor], [])\n  File \"code/__torch__/torch/nn/modules/container/___torch_mangle_2.py\", line 14, in forward\n    _1 = getattr(self, \"1\")\n    _2 = getattr(self, \"2\")\n    input0 = (_0).forward(input, )\n              ~~~~~~~~~~~ <--- HERE\n    input1 = (_1).forward(input0, )\n    return (_2).forward(input1, )\n  File \"code/__torch__/torch/nn/modules/conv/___torch_mangle_0.py\", line 23, in forward\n    weight = self.weight\n    bias = self.bias\n    _0 = (self)._conv_forward(input, weight, bias, )\n          ~~~~~~~~~~~~~~~~~~~ <--- HERE\n    return _0\n  def _conv_forward(self: __torch__.torch.nn.modules.conv.___torch_mangle_0.Conv2d,\n  File \"code/__torch__/torch/nn/modules/conv/___torch_mangle_0.py\", line 29, in _conv_forward\n    weight: Tensor,\n    bias: Optional[Tensor]) -> Tensor:\n    _1 = torch.conv2d(input, weight, bias, [1, 1], [0, 0], [1, 1])\n         ~~~~~~~~~~~~ <--- HERE\n    return _1\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"/raid/scratch/stanojevicd/projects/haec-BigBird/model.py\", line 157, in forward\n        sliced_sequences_concatenated = torch.cat(encoded)'''\n        x = x.permute((0, 3, 1, 2))\n        sliced_sequences_concatenated = self.qn(x, target_positions, lengths)\n                                        ~~~~~~~ <--- HERE\n    \n        # list of tensors of shape (selected_token_number, 1) -> (selected_token_number)\n  File \"/raid/scratch/stanojevicd/projects/haec-BigBird/transformer.py\", line 37, in forward\n                lengths: Tensor) -> Tensor:\n        x = self.context_read(x)  # [B, I, L, R] -> [B, 128, L, R]\n        x = self.context_pos(x)  # [B, 128, L, R] -> [B, 256, L, 1]\n            ~~~~~~~~~~~~~~~~ <--- HERE\n        x = x.squeeze(-1).transpose(1, 2)  # [B, L, 256]\n    \n  File \"/home/stanojevicd/miniforge3/envs/haec/lib/python3.11/site-packages/torch/nn/modules/container.py\", line 215, in forward\n    def forward(self, input):\n        for module in self:\n            input = module(input)\n                    ~~~~~~ <--- HERE\n        return input\n  File \"/home/stanojevicd/miniforge3/envs/haec/lib/python3.11/site-packages/torch/nn/modules/conv.py\", line 460, in forward\n    def forward(self, input: Tensor) -> Tensor:\n        return self._conv_forward(input, self.weight, self.bias)\n               ~~~~~~~~~~~~~~~~~~ <--- HERE\n  File \"/home/stanojevicd/miniforge3/envs/haec/lib/python3.11/site-packages/torch/nn/modules/conv.py\", line 456, in _conv_forward\n                            weight, bias, self.stride,\n                            _pair(0), self.dilation, self.groups)\n        return F.conv2d(input, weight, bias, self.stride,\n               ~~~~~~~~ <--- HERE\n                        self.padding, self.dilation, self.groups)\nRuntimeError: GET was unable to find an engine to execute this computation\n")
[00:01:36] Processing 2/? batch ⠁
[>---------------------------------------] 1065/63886                                                                       0:     0x591688e8d8d5 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
   1:     0x591688dc9bab - core::fmt::write::h4b5a1270214bc4a7
   2:     0x591688e8b80f - std::io::Write::write_fmt::hd04af345a50c312d
   3:     0x591688e8e6b1 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
   4:     0x591688e8e397 - std::panicking::default_hook::h3cacb9c27561ad33
   5:     0x591688e8ee66 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   6:     0x591688e8eb87 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   7:     0x591688e8dd99 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   8:     0x591688e8e804 - rust_begin_unwind
   9:     0x591688d59833 - core::panicking::panic_fmt::h3d8fc78294164da7
  10:     0x591688d59c66 - core::result::unwrap_failed::hfa79a499befff387
  11:     0x591688dee7fa - herro::inference::inference::h214be8024a091816
  12:     0x591688e3d5f3 - herro::inference::inference_worker::hfc7c79a2578b9e38
  13:     0x591688df7aec - std::sys::backtrace::__rust_begin_short_backtrace::h0f46a19c868e79c5
  14:     0x591688e2c6e5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdebeac8aadf2aa2f
  15:     0x591688e91e9b - std::sys::pal::unix::thread::Thread::new::thread_start::ha8af9c992ef0b208
  16:     0x7d8265e6bac3 - <unknown>
  17:     0x7d8265efd850 - <unknown>
  18:                0x0 - <unknown>
Aborted (core dumped)

Is there any suggestion or solution here?

Thanks,
Shuo

**Comment by unavailable-2374** [comment]
when I added "-d 0,1,2,3,4,5,6,7", the erro changed:

  thread '<unnamed>' panicked at src/inference.rs:184:64:
  called `Result::unwrap()` on an `Err` value: Torch("The following operation failed in the TorchScript interpreter.\nTrace
  back of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__/transformer.py\", line 26, in forw
  ard\n      _2 = torch.select(x2, 0, i)\n      _3 = annotate(List[Optional[Tensor]], [tp])\n      _4 = torch.append(batch,
   torch.index(_2, _3))\n                               ~~~~~~~~~~~ <--- HERE\n    x3 = _0(batch, True, 0., )\n    _5 = __t
  orch__.transformer.create_mask(lengths, )\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"/
  raid/scratch/stanojevicd/projects/haec-BigBird/transformer.py\", line 40, in forward\n        x = x.squeeze(-1).transpose
  (1, 2)  # [B, L, 256]\n    \n        batch = [x[i, tp] for i, tp in enumerate(target_positions)]\n                 ~~~~~~
  ~~ <--- HERE\n        x = nn.utils.rnn.pad_sequence(batch, True)\n        mask = create_mask(lengths).to(device=x.device)
  \nRuntimeError: CUDA error: an illegal memory access was encountered\nCompile with `TORCH_USE_CUDA_DSA` to enable device-
  side assertions.\n\n")
  stack backtrace:
     0:     0x5cba913c78d5 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9
  dad2a88e955ff
     1:     0x5cba91303bab - core::fmt::write::h4b5a1270214bc4a7
     2:     0x5cba913c580f - std::io::Write::write_fmt::hd04af345a50c312d
     3:     0x5cba913c86b1 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
     4:     0x5cba913c8397 - std::panicking::default_hook::h3cacb9c27561ad33
     5:     0x5cba913c8e66 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
     6:     0x5cba913c8b87 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
     7:     0x5cba913c7d99 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
     8:     0x5cba913c8804 - rust_begin_unwind
     9:     0x5cba91293833 - core::panicking::panic_fmt::h3d8fc78294164da7
    10:     0x5cba91293c66 - core::result::unwrap_failed::hfa79a499befff387
    11:     0x5cba913287fa - herro::inference::inference::h214be8024a091816
    12:     0x5cba913775f3 - herro::inference::inference_worker::hfc7c79a2578b9e38
    13:     0x5cba91331aec - std::sys::backtrace::__rust_begin_short_backtrace::h0f46a19c868e79c5
    14:     0x5cba913666e5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdebeac8aadf2aa2f
    15:     0x5cba913cbe9b - std::sys::pal::unix::thread::Thread::new::thread_start::ha8af9c992ef0b208
    16:     0x7de2f0e6bac3 - <unknown>
    17:     0x7de2f0efd850 - <unknown>
    18:                0x0 - <unknown>
    thread '<unnamed>' panicked at src/inference.rs:184:64:
  called `Result::unwrap()` on an `Err` value: Torch("The following operation failed in the TorchScript interpreter.\nTrace
  back of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__/transformer.py\", line 26, in forw
  ard\n      _2 = torch.select(x2, 0, i)\n      _3 = annotate(List[Optional[Tensor]], [tp])\n      _4 = torch.append(batch,
   torch.index(_2, _3))\n                               ~~~~~~~~~~~ <--- HERE\n    x3 = _0(batch, True, 0., )\n    _5 = __t
  orch__.transformer.create_mask(lengths, )\n\nTraceback of TorchScript, original code (most recent call last):\n  File \"/raid/scratch/stanojevicd/projects/haec-BigBird/transformer.py\", line 40, in forward\n        x = x.squeeze(-1).transpose(1, 2)  # [B, L, 256]\n    \n        batch = [x[i, tp] for i, tp in enumerate(target_positions)]\n                 ~~~~~~~~ <--- HERE\n        x = nn.utils.rnn.pad_sequence(batch, True)\n        mask = create_mask(lengths).to(device=x.device)\nRuntimeError: CUDA error: an illegal memory access was encountered\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n")
  Aborted (core dumped)
